### ISSUE TITLE
Missing package elastos-supernode-20190616-alpha.tgz

### ISSUE THREAD

**Issue by MButcho** [cyber-republic/supernode-setup#2]
wget https://download.elastos.org/supernode/elastos-supernode-20190616-alpha.tgz
--2020-05-09 19:38:56--  https://download.elastos.org/supernode/elastos-supernode-20190616-alpha.tgz
Resolving download.elastos.org (download.elastos.org)... 104.16.148.30, 104.16.233.72, 2606:4700::6810:e948, ...
Connecting to download.elastos.org (download.elastos.org)|104.16.148.30|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-05-09 19:38:57 ERROR 404: Not Found.

Update with new package ;)

**Comment by z0uz** [comment]
seems like nobody care - still missing tho.

**Comment by MButcho** [comment]
Replace by different distribution: https://github.com/elastos/Elastos.Node/blob/master/SUMMARY.md
